version: 2.0

jobs:
  test:
    docker:
      - image: circleci/node:latest
    working_directory: ~/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-cache-v1-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - dependencies-cache-v1-{{ arch }}-{{ .Branch }}
            - dependencies-cache-v1
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependencies-cache-v1-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules
  quality:
    docker:
      - image: circleci/openjdk:latest
      - image: circleci/node:latest
    working_directory: ~/node
    steps:
      - checkout
      - run:
          name: Install Sonar Scanner
          command: cd && sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip && sudo unzip sonar-scanner-cli-3.3.0.1492-linux.zip && sudo rm sonar-scanner-cli-3.3.0.1492-linux.zip
      - restore_cache:
          keys:
            - dependencies-cache-v1-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - dependencies-cache-v1-{{ arch }}-{{ .Branch }}
            - dependencies-cache-v1
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependencies-cache-v1-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - node_modules
workflows:
  version: 2
  quality:
    jobs:
      - quality
